services:
  - type: web
    name: isoform-dashboard-a8g4k2j7x
    env: python
    plan: free
    rootDir: isoform_dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard_app.py --input data/distributions_condition_sum.tsv --exons data/expressed_isoforms.positions.txt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
